auctions/biders/urls.py
from django.urls import path
from . import views

app_name = 'biders'


urlpatterns = [
    path ('', views.index, name="index"),
    path ('bidnow/', views.bidnow, name="bidnow"),
    
]

auctions/urls.py
from django.urls import path
from . import views


app_name = "auctions"

urlpatterns = [
    path("create/", views.create_auction, name="auction_create"),
]

core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("auctions/", views.auctions, name="auctions")
]

sara/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    # path('', include('users.urls')),
    # path('auctions/', include('auctions.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

users/urls.py
from django.urls import include, path
from . import views

app_name = "users"

urlpatterns = [
    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

auctions/models.py
from django.db import models

core/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

auctions/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.decorators import login_required


@login_required
def create_auction(request: HttpRequest) -> HttpResponse:
    # if not request.user.is_authenticated:
    #     return redirect(settings.LOGIN_URL)
    return render(request, "auctions/auction_form.html")

core/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "core/index.html")


def contact(request: HttpRequest) -> HttpResponse:
    return render(request, "core/contact.html")


def about(request: HttpRequest) -> HttpResponse:
    return render(request, "core/about.html")


def auctions(request: HttpRequest) -> HttpResponse:
    return render(request, "core/auctions.html")

users/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse


def login(request: HttpRequest) -> HttpResponse:
    return render(request, "registration/login.html")

auctions/biders/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biders</title>
    
    <link  href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="main">
        <div class="navbar">
            <div class="icon">
                <h2 class="logo" >ARSA</h2>
                <p class="plogo">Lorem ipsum, dolor sit amet consectetur adipisicing elit.<br> Ex vel voluptate sequi, omnis ratione optio, eaque soluta<br> est fugiat officiis accusantium dolore possimus magnam<br> odit laborum, aspernatur veritatis iste? Quibusdam?<br><br>-- ARSA Team</p>
            </div>
            <div class="form">
                <h2>Log In Here</h2>
                <input type="email" name="email" placeholder="Enter e-mail here">
                <input type="password" name="" placeholder="Enter password here">
                <button class="btn"><a href="#">Login</a></button>

                <p class="link">Don't have an account?!</p>
                <a href="#">Sign Up here...</a>
            </div>
            <div class="vl">
                <span class="vl-innertext">or</span>
              </div>
            <div class="crebid">
                <button class="createbtn"><a href="#" title="Create an auction">Create</a></button>
                <button class="bidbtn"><a href="bidnow" title="Bid for auctions">Bid Now</a></button>


            </div>
        </div>
        

    </div>
    
</body>
</html>

auctions/templates/auctions/auction_form.html
{% extends 'base.html' %}

{% block content %}
<h1>There will be a form to add new auctions here ...</h1>
{% endblock content %}

auctions/templates/auctions/bidnow.html
{% extends 'base.html' %}

core/templates/base.html
<!DOCTYPE html>{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Auctions Website" />
    <meta
      name="author"
      content="Sabire, Arsen, Regi, Amarildo and contributors"
    />
    <title>{% block title %}Auctions · SARA{% endblock title %}</title>
    {% block styles %}
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
    {% endblock styles %}
    {% block extrastyles %}{% endblock extrastyles %}
  </head>
  <body class="d-flex flex-column h-100">
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'core:index' %}">SARA</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a
                  class="nav-link active"
                  aria-current="page"
                  href="{% url 'core:index' %}"
                  >Home</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:auctions' %}">Auctions</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'core:contact' %}" class="nav-link">Contact</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'core:about' %}" class="nav-link">About</a>
              </li>
            </ul>
            <form class="d-flex">
              <input
                class="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <button class="btn btn-outline-success" type="submit">
                Search
              </button>
            </form>
          </div>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main class="flex-shrink-0">
      <div class="container">{% block content %}{% endblock content %}</div>
    </main>

    <footer class="footer mt-auto py-3 bg-light">
      <div class="container">
        <p class="text-muted text-center m-0">
          Copyright &copy; 2021 &mdash; SARA Auctions
        </p>
      </div>
    </footer>

    {% block scripts %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    {% endblock scripts %} {% block extrascripts %}{% endblock extrascripts %}
  </body>
</html>

core/templates/core/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About us</h1>
{% endblock content %}

core/templates/core/auctions.html
{% extends 'base.html' %}

{% block content %}
<h1>Auctions</h1>
{% endblock content %}

core/templates/core/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>Contact Us</h1>
{% endblock content %}

core/templates/core/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Auctions Website" />
    <meta
      name="author"
      content="Sabire, Arsen, Regi, Amarildo and contributors"
    />
    <title>Auctions · SARA</title>
    <!-- <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    /> -->
    <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
  </head>
  <body class="d-flex flex-column h-100">
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'core:index' %}">SARA</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a
                  class="nav-link active"
                  aria-current="page"
                  href="{% url 'core:index' %}"
                  >Home</a
                >
              </li>
              <li class="nav-item">
                <a href="{% url 'core:auctions' %}" class="nav-link">Auctions</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'core:contact' %}" class="nav-link">Contact</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'core:about' %}" class="nav-link">About</a>
              </li>
            </ul>
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav mb-2 mb-md-0">
              <li class="nav-item">
                <a href="" class="nav-link">Welcome {{ request.user.get_full_name|default:request.user.username }}</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'users:logout' %}" class="nav-link">Logout</a>
              </li>
            </ul>
            {% else %}
            <form class="d-flex" method="POST" action="{% url 'users:login' %}">
              {% csrf_token %}
              <input
                class="form-control me-2"
                type="text"
                placeholder="Username"
                aria-label="Username"
                name="username"
              />
              <input
                type="password"
                class="form-control me-2"
                name="password"
                placeholder="Password"
                aria-label="Password"
              />
              <button class="btn btn-primary" type="submit">
                Login
              </button>
            </form>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>
    
    <!-- Begin page content -->
    <main class="flex-shrink-0">
      <div class="container-fluid p-0">
        <div id="home-wrapper">
          {% if not request.user.is_authenticated %}
          <div id="signup-callout" class="p-4 rounded-3 m-2">
            <p class="text-center mb-0">
              Don't have an account?<br>
              <a href="" class="link-info">Sign up here &hellip;</a>
            </p>
          </div>
          {% endif %}
          <div class="home-actions">
            <a href="{% url 'auctions:auction_create' %}" class="btn btn-secondary">New Auction</a>
            <span class="actions-connector">or</span>
            <a href="" class="btn btn-primary">Bid Now</a>
          </div>
        </div>
      </div>
    </main>
    {% block content %}
    <div class="home_page_h_1">
      <h1>Home Page</h1>
    </div>
    {% endblock content %}
    <footer id="home-footer" class="footer mt-auto py-3">
      <div class="container">
        <p class="text-center m-0">
          Copyright &copy; 2021 &mdash; SARA Auctions
        </p>
      </div>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/base.html
<!DOCTYPE html>{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Auctions Website" />
    <meta
      name="author"
      content="Sabire, Arsen, Regi, Amarildo and contributors"
    />
    <title>{% block title %}Auctions · SARA{% endblock title %}</title>
    {% block styles %}
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'styles/main.css' %}" type="text/css" />
    {% endblock styles %}
    {% block extrastyles %}{% endblock extrastyles %}
  </head>
  <body class="d-flex flex-column h-100">
    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'core:index' %}">SARA</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a
                  class="nav-link active"
                  aria-current="page"
                  href="{% url 'core:index' %}"
                  >Home</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:auctions' %}">Auctions</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'core:contact' %}" class="nav-link">Contact</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'core:about' %}" class="nav-link">About</a>
              </li>
            </ul>
            <form class="d-flex">
              <input
                class="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <button class="btn btn-outline-success" type="submit">
                Search
              </button>
            </form>
          </div>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main class="flex-shrink-0">
      <div class="container">{% block content %}{% endblock content %}</div>
    </main>

    <footer class="footer mt-auto py-3 bg-light">
      <div class="container">
        <p class="text-muted text-center m-0">
          Copyright &copy; 2021 &mdash; SARA Auctions
        </p>
      </div>
    </footer>

    {% block scripts %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    {% endblock scripts %} 
    {% block extrascripts %}
    {% endblock extrascripts %}
  </body>
</html>